baseURL = "https://iirconf.github.io/IIR2025/"
title = "IIR 2025"
author = "IIR Committee"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[params]

  showBlog = false
  mainSections = ['news']

  googleFonts = true

  [params.logo]
    main = "img/logo/IIR25_temporary_colored_logo.png"
    alt = "IIR 2025 Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-15"

  [params.site]
    name = "IIR 2025"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "15th Italian Information Retrieval Workshop - 3 - 5 September 2025, Cagliari, Italy"
    meta_og_title = "IIR 2025"
    meta_og_type = "website"
    meta_og_url = "https://IIRConf.github.io/IIR2025"
    meta_og_description = "15th Italian Information Retrieval Workshop - 3 - 5 September 2025, Cagliari, Italy"
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@iir2025"
    meta_twitter_creator = "@iir2025"

[menu]

  # Main Navigation Menu
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "cfp"
    name = "Call for Papers"
    url = "/call-for-papers/"
    weight = 2

  [[menu.main]]
    name = "Author Guidelines"
    url = "#"
    weight = 3

    [[menu.main]]
      parent = "Author Guidelines"
      name = "ACM Policy on Authorship"
      url = "https://www.acm.org/publications/policies/new-acm-policy-on-authorship"
      weight = 1
    
    [[menu.main]]
      parent = "Author Guidelines"
      name = "ACM Policy on the Use of Artificial Intelligence"
      url = "https://www.acm.org/publications/policies/frequently-asked-questions#h-can-i-use-generative-ai-software-tools-to-prepare-my-manuscript?"
      weight = 2
    
    [[menu.main]]
      parent = "Author Guidelines"
      name = "ACM Policy on Plagiarism, Misrepresentation, and Falsification"
      url = "https://www.acm.org/publications/policies/plagiarism-overview"
      weight = 3

    [[menu.main]]
      parent = "Author Guidelines"
      name = "ACM Inappropriate Content Policy"
      url = "https://www.acm.org/publications/policies/inappropriate-content-policy"
      weight = 4

    [[menu.main]]
      parent = "Author Guidelines"
      name = "ACM Policy Against Harassment"
      url = "https://www.acm.org/about-acm/policy-against-harassment"
      weight = 5

    [[menu.main]]
      parent = "Author Guidelines"
      name = "ACM Privacy Policy"
      url = "https://www.acm.org/about-acm/privacy-policy"
      weight = 6

  [[menu.main]]
    identifier = "dates"
    name = "Important Dates"
    url = "/important-dates/"
    weight = 4

  [[menu.main]]
    identifier = "attending"
    name = "Attending"
    url = "/attending/"
    weight = 5
  
  [[menu.main]]
    identifier = "organizers"
    name = "Organizing Committee"
    url = "/organizers/"
    weight = 6
